config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views
from .views import (
    IndexView,
    MailingListView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    MessageListView,
    ClientListView,
    AttemptListView,
    SendMailingView,
    ClientCreateView,
    MessageCreateView, MessageUpdateView, MessageDeleteView,
)

app_name = "mailing"


class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("mailings/", MailingListView.as_view(), name="list"),
    path("mailings/create/", MailingCreateView.as_view(), name="create"),
    path(
        "mailings/<int:pk>/update/", MailingUpdateView.as_view(), name="update"
    ),
    path(
        "mailings/<int:pk>/delete/", MailingDeleteView.as_view(), name="delete"
    ),
    path("mailings/<int:pk>/send/", SendMailingView.as_view(), name="send"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("logs/", AttemptListView.as_view(), name="log_list"),
    path(
        "clients/<int:pk>/update/",
        views.ClientUpdateView.as_view(),
        name="client_update",
    ),
    path(
        "clients/<int:pk>/delete/",
        views.ClientDeleteView.as_view(),
        name="client_delete",
    ),
    path(
        "accounts/logout/",
        csrf_exempt(CustomLogoutView.as_view()),
        name="logout",
    ),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path(
        "messages/create/", MessageCreateView.as_view(), name="message_create"
    ),
    path("messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    RegisterView,
    VerifyEmailView, UserUpdateView, ProfileView,
)
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "verify/<uidb64>/<token>/",
        VerifyEmailView.as_view(),
        name="verify_email",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            success_url=reverse_lazy("users:password_reset_done"),
            email_template_name="registration/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/edit/", UserUpdateView.as_view(), name="profile_edit"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Mailing Service</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav>
<ul>
  <li><a href="{% url 'mailing:list' %}">Список рассылок</a></li>
  <li><a href="{% url 'mailing:message_list' %}">Список сообщений</a></li>
  <li><a href="{% url 'mailing:client_list' %}">Список клиентов</a></li>
  <li><a href="{% url 'mailing:log_list' %}">История отправок</a></li>
</ul>
</nav>
<div class="container mt-4">
  <header>
    {% if user.is_authenticated %}
    <p>
      Привет, {{ user.username }}
      | <a href="{% url 'users:profile' %}">Профиль</a>
      | <a href="{% url 'users:profile_edit' %}">Редактировать</a>
      |
    <form method="post" action="{% url 'users:logout' %}" style="display:inline;">
      {% csrf_token %}
      <button type="submit" class="btn btn-link p-0 m-0 align-baseline">Выйти</button>
    </form>
    </p>
    {% else %}
  <p>
    <a href="{% url 'users:login' %}">Войти</a> |
    <a href="{% url 'users:register' %}">Регистрация</a>
  </p>
{% endif %}
  </header>
  {% block content %}{% endblock %}
</div>
</body>
</html>